spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/h2DB/swagger;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: root
    password: 
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  jersey:
    type: filter
    
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

info:
    artifact: SpringJerseySwagger
    name: SpringJerseySwagger
    description: Spring Jersey Swagger
    version: 1.0.0
    